import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { cn } from '@/lib/utils';
import './globals.css';
import {Providers} from "./provider/providerNextjs";
import Navbar from './components/Navbar';
import {Button, ButtonGroup} from "@nextui-org/react";



const inter = Inter({ subsets: ['latin'], variable: '--font-sans' });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en"  className='light'>
      <body
        className={cn(
          'min-h-screen bg-background font-sans antialiased',
          inter.variable
        )}
      >
                <Providers>
                <Button color="primary">
      Button
    </Button>
                          {children}
        </Providers>

      </body>
    </html>
  );
}
